name: Giveaways
version: '${project.version}'
main: me.wacko.giveaways.Giveaways
api-version: '1.20'
softdepend: [PlaceholderAPI]

commands:
  giveaways:
    description: opens a gui of all active giveaways
  giveaway:
    description: set of subcommands for giveaway creation
    usage: /<command> [create|create <duration>|forcestop]

permissions:
  giveaways.command:
    description: allows the opening of the giveaway gui
  giveaways.start:
    description: allows a player to start a giveaway
  giveaways.admin:
    description: adds all admin commands
  giveaways.duration:
    description: allows a duration to be set
  giveaways.*:
    description: all giveaways permissions
    default: false
    children:
      giveaways.command: true
      giveaways.start: true
      giveaways.duration: true